ALERTS = {
    "service_critical": {
        "payload": {
            "type": "SERVICE",
            "notification_type": "PROBLEM",
            "hostname": "web-server-01",
            "host_address": "192.168.1.10",
            "host_display_name": "Web Server 01",
            "service_desc": "HTTP",
            "service_display_name": "HTTP Service",
            "service_state": "CRITICAL",
            "service_output": "HTTP CRITICAL - Socket timeout after 10 seconds",
            "long_service_output": "",
            "timestamp": "Mon Feb 24 10:30:00 UTC 2026",
            "notification_author": "",
            "notification_comment": "",
        },
    },
    "service_warning": {
        "payload": {
            "type": "SERVICE",
            "notification_type": "PROBLEM",
            "hostname": "db-server-01",
            "host_address": "192.168.1.20",
            "host_display_name": "Database Server 01",
            "service_desc": "Disk Usage",
            "service_display_name": "Disk Usage - /var",
            "service_state": "WARNING",
            "service_output": "DISK WARNING - /var is 85% full (used 170GB of 200GB)",
            "long_service_output": "/var: 170GB/200GB (85%)\nLargest directory: /var/log (45GB)",
            "timestamp": "Mon Feb 24 10:35:00 UTC 2026",
            "notification_author": "",
            "notification_comment": "",
        },
    },
    "service_recovery": {
        "payload": {
            "type": "SERVICE",
            "notification_type": "RECOVERY",
            "hostname": "web-server-01",
            "host_address": "192.168.1.10",
            "host_display_name": "Web Server 01",
            "service_desc": "HTTP",
            "service_display_name": "HTTP Service",
            "service_state": "OK",
            "service_output": "HTTP OK - 200 response in 0.052s",
            "long_service_output": "",
            "timestamp": "Mon Feb 24 10:45:00 UTC 2026",
            "notification_author": "",
            "notification_comment": "",
        },
    },
    "host_down": {
        "payload": {
            "type": "HOST",
            "notification_type": "PROBLEM",
            "hostname": "app-server-03",
            "host_address": "192.168.1.30",
            "host_display_name": "Application Server 03",
            "host_state": "DOWN",
            "host_output": "PING CRITICAL - Packet loss = 100%",
            "long_host_output": "",
            "timestamp": "Mon Feb 24 11:00:00 UTC 2026",
            "notification_author": "",
            "notification_comment": "",
        },
    },
    "host_recovery": {
        "payload": {
            "type": "HOST",
            "notification_type": "RECOVERY",
            "hostname": "app-server-03",
            "host_address": "192.168.1.30",
            "host_display_name": "Application Server 03",
            "host_state": "UP",
            "host_output": "PING OK - Packet loss = 0%, RTA = 1.23ms",
            "long_host_output": "",
            "timestamp": "Mon Feb 24 11:15:00 UTC 2026",
            "notification_author": "",
            "notification_comment": "",
        },
    },
    "host_acknowledged": {
        "payload": {
            "type": "HOST",
            "notification_type": "ACKNOWLEDGEMENT",
            "hostname": "app-server-03",
            "host_address": "192.168.1.30",
            "host_display_name": "Application Server 03",
            "host_state": "DOWN",
            "host_output": "PING CRITICAL - Packet loss = 100%",
            "long_host_output": "",
            "timestamp": "Mon Feb 24 11:05:00 UTC 2026",
            "notification_author": "admin",
            "notification_comment": "Investigating network issue in rack 3",
        },
    },
}
